# Generated by Django 5.2.2 on 2026-09-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegacionesAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacion',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='delegacion',
            name='encargado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='delegacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
