# Generated by Django 5.2.2 on 2026-09-29 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delegacionesAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCiudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alumbrado', 'Alumbrado Público'), ('baches', 'Baches y Pavimento'), ('basura', 'Recolección de Residuos'), ('seguridad', 'Seguridad Ciudadana'), ('verde', 'Áreas Verdes'), ('otros', 'Otros')], max_length=20)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('analisis', 'En Análisis'), ('derivado', 'Derivado a Departamento'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='delegacionesAPP.delegacion')),
            ],
        ),
    ]
