# Generated by Django 5.2.2 on 2026-09-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportesCiudadanosAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteciudadano',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reporteciudadano',
            name='ubicacion',
            field=models.CharField(max_length=200),
        ),
    ]
