# Generated by Django 5.2.2 on 2026-09-29 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delegacionesAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion_riesgo', models.TextField()),
                ('nivel_peligro', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='medio', max_length=20)),
                ('coordenadas_aprox', models.CharField(blank=True, max_length=255, null=True)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_riesgo', to='delegacionesAPP.delegacion')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='delegacionesAPP.delegacion')),
                ('zona_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emergenciasTerritorialesAPP.zonariesgo')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('preventiva', 'Preventiva'), ('alerta', 'Alerta'), ('emergencia', 'Emergencia')], default='preventiva', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='emergenciasTerritorialesAPP.zonariesgo')),
            ],
        ),
    ]
