# Generated by Django 5.2.2 on 2026-09-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergenciasTerritorialesAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contactoemergencia',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactoemergencia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zonariesgo',
            name='coordenadas_aprox',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zonariesgo',
            name='descripcion_riesgo',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='zonariesgo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
